<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="TargetFramework">

	<PropertyGroup>
		<!-- 覆盖仓库的多目标配置，并避免 solution -f 将本项目错误地强制为具体运行时。 -->
		<TargetFrameworks></TargetFrameworks>
		<TargetFramework>netstandard2.1</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>

		<Version>3.5.17</Version>
		<PackageId>Fast.IaaS</PackageId>
		<Description>Fast.NET 框架基础设施模块库。</Description>
	</PropertyGroup>

</Project>
