<Project>

    <PropertyGroup>
        <RepositoryRoot>$(MSBuildThisFileDirectory)</RepositoryRoot>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <LangVersion>14.0</LangVersion>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <PackageVersion>$(Version)</PackageVersion>

        <Authors>小方</Authors>
        <Product>Fast.NET</Product>
        <Description>面向 ASP.NET Core 的模块化 .NET SDK。</Description>
        <PackageTags>Fast.NET;ASP.NET Core;.NET;SDK;Cross Platform</PackageTags>
        <Copyright>版权所有 © 2018-Now 小方</Copyright>
        <PackageProjectUrl>https://fastdotnet.com</PackageProjectUrl>
        <RepositoryUrl>https://gitee.com/FastDotnet/Fast.NET</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageIcon>Fast.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageOutputPath>$(RepositoryRoot)nupkgs</PackageOutputPath>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <SatelliteResourceLanguages>en-US;zh-CN</SatelliteResourceLanguages>

        <!-- 避免多个目标框架在构建阶段重复生成 OpenAPI 文档。 -->
        <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
    </PropertyGroup>

    <ItemGroup Condition="'$(IsPackable)' != 'false'">
        <None Include="$(RepositoryRoot)README.md" Pack="true" PackagePath="\" />
        <None Include="$(RepositoryRoot)README.zh.md" Pack="true" PackagePath="\" />
        <None Include="$(RepositoryRoot)LICENSE" Pack="true" PackagePath="\" />
        <None Include="$(RepositoryRoot)Fast.png" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
