<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>3.5.9</Version>
		<PackageId>Fast.Consul</PackageId>
		<Description>Fast.NET 框架Consul模块库。</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="$(RepositoryRoot)src\Runtime\Fast.Runtime.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Consul" />
	</ItemGroup>

</Project>
