<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>3.5.22</Version>
		<PackageId>Fast.Mapster</PackageId>
		<Description>Fast.NET 框架对象映射模块库。</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="$(RepositoryRoot)src\Runtime\Fast.Runtime.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Mapster" />
		<PackageReference Include="Mapster.DependencyInjection" />
	</ItemGroup>

</Project>
