<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>3.5.26</Version>
		<PackageId>Fast.Serialization.Newtonsoft.Json</PackageId>
        <RootNamespace>Fast.Serialization</RootNamespace>
		<Description>Fast.NET 框架 Newtonsoft.Json 序列化模块库。</Description>
	</PropertyGroup>

	<!-- 使用 ASPNETCore.App 包 -->
	<!-- https://learn.microsoft.com/zh-cn/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-8.0&tabs=visual-studio -->
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
        <PackageReference Include="Newtonsoft.Json" />
	</ItemGroup>

</Project>
