<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>3.5.9</Version>
		<PackageId>Fast.OpenApi</PackageId>
		<Description>Fast.NET 框架 OpenApi 模块库。</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="$(SolutionDir)src\Runtime\Fast.Runtime.csproj" />
	</ItemGroup>

</Project>